[theme]
primaryColor = "#2B3A42"  # Dark Gray (Header)
backgroundColor = "#F4F4F6"  # Neutral Light Gray (Body)
secondaryBackgroundColor = "#FFFFFF"  # White (Cards, Containers)
textColor = "#333333"  # Dark Gray (Text)
font = "sans serif"  # Consistent with the website
